/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datamobil;

/**
 *
 * @author CodeLab240619
 */
public class WelcomePage extends javax.swing.JFrame {

    /**
     * Creates new form WelcomePage
     */
    public WelcomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        MenuHome = new javax.swing.JLabel();
        MenuDataMobil = new javax.swing.JLabel();
        MenuTransaksi = new javax.swing.JLabel();
        MenuUser = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        MenuLogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));

        MenuHome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MenuHome.setForeground(new java.awt.Color(255, 255, 255));
        MenuHome.setText("Home");
        MenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuHomeMouseClicked(evt);
            }
        });

        MenuDataMobil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MenuDataMobil.setForeground(new java.awt.Color(204, 204, 204));
        MenuDataMobil.setText("Data Mobil");
        MenuDataMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuDataMobilMouseClicked(evt);
            }
        });

        MenuTransaksi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MenuTransaksi.setForeground(new java.awt.Color(204, 204, 204));
        MenuTransaksi.setText("Transaksi");
        MenuTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuTransaksiMouseClicked(evt);
            }
        });

        MenuUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MenuUser.setForeground(new java.awt.Color(204, 204, 204));
        MenuUser.setText("User");
        MenuUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuUserMouseClicked(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));

        MenuLogout.setBackground(new java.awt.Color(204, 204, 204));
        MenuLogout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MenuLogout.setForeground(new java.awt.Color(204, 204, 204));
        MenuLogout.setText("Logout");
        MenuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MenuHome)
                            .addComponent(MenuDataMobil)
                            .addComponent(MenuTransaksi)
                            .addComponent(MenuUser)
                            .addComponent(MenuLogout))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuHome)
                .addGap(18, 18, 18)
                .addComponent(MenuDataMobil)
                .addGap(18, 18, 18)
                .addComponent(MenuTransaksi)
                .addGap(18, 18, 18)
                .addComponent(MenuUser)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuLogout)
                .addContainerGap(314, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 767, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHomeMouseClicked
        // TODO add your handling code here:
        WelcomePage welcomePage = new WelcomePage();
        FormDataMobil formDataMobil = new FormDataMobil();
        FAnggota formAnggota = new FAnggota();
        FSewa formSewa = new FSewa();
        Login login = new Login();
        
        this.setVisible(true);
        formDataMobil.setVisible(false);
        formAnggota.setVisible(false);
        formSewa.setVisible(false);
        login.setVisible(false);
    }//GEN-LAST:event_MenuHomeMouseClicked

    private void MenuDataMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDataMobilMouseClicked
        // TODO add your handling code here:
        WelcomePage welcomePage = new WelcomePage();
        FormDataMobil formDataMobil = new FormDataMobil();
        FAnggota formAnggota = new FAnggota();
        FSewa formSewa = new FSewa();
        Login login = new Login();
        
        this.setVisible(false);
        formDataMobil.setVisible(true);
        formAnggota.setVisible(false);
        formSewa.setVisible(false);
        login.setVisible(false);
    }//GEN-LAST:event_MenuDataMobilMouseClicked

    private void MenuTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuTransaksiMouseClicked
        // TODO add your handling code here:
        WelcomePage welcomePage = new WelcomePage();
        FormDataMobil formDataMobil = new FormDataMobil();
        FAnggota formAnggota = new FAnggota();
        FSewa formSewa = new FSewa();
        Login login = new Login();
        
        this.setVisible(false);
        formDataMobil.setVisible(false);
        formAnggota.setVisible(false);
        formSewa.setVisible(true);
        login.setVisible(false);
    }//GEN-LAST:event_MenuTransaksiMouseClicked

    private void MenuUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuUserMouseClicked
        // TODO add your handling code here:
        WelcomePage welcomePage = new WelcomePage();
        FormDataMobil formDataMobil = new FormDataMobil();
        FAnggota formAnggota = new FAnggota();
        FSewa formSewa = new FSewa();
        Login login = new Login();
        
        this.setVisible(false);
        formDataMobil.setVisible(false);
        formAnggota.setVisible(true);
        formSewa.setVisible(false);
        login.setVisible(false);
    }//GEN-LAST:event_MenuUserMouseClicked

    private void MenuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLogoutMouseClicked
        // TODO add your handling code here:
        WelcomePage welcomePage = new WelcomePage();
        FormDataMobil formDataMobil = new FormDataMobil();
        FAnggota formAnggota = new FAnggota();
        FSewa formSewa = new FSewa();
        Login login = new Login();
        
        this.setVisible(false);
        formDataMobil.setVisible(false);
        formAnggota.setVisible(false);
        formSewa.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_MenuLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuDataMobil;
    private javax.swing.JLabel MenuHome;
    private javax.swing.JLabel MenuLogout;
    private javax.swing.JLabel MenuTransaksi;
    private javax.swing.JLabel MenuUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
